# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-54224d3c-5d0a-45c2-b2a5-1cdddbbfc860";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-54224d3c-5d0a-45c2-b2a5-1cdddbbfc860".device = "/dev/disk/by-uuid/54224d3c-5d0a-45c2-b2a5-1cdddbbfc860";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A34E-FCB0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
