{ config, lib, pkgs, ... }:

let
    keybindsLua = pkgs.writeText "keybinds.lua" ''
        -- Generated by NixOS home-manager. Overwrites end-4's placeholder
        -- ~/.config/hypr/custom/keybinds.lua on every home-manager switch.

        -- ===== Per-host Hyprland settings (laptop) =====
        hl.config({
            input = {
                kb_layout = "be",
                numlock_by_default = true,
                follow_mouse = 2,
                sensitivity = 0,
                accel_profile = "flat",
                touchpad = { natural_scroll = true },
            },
            misc = { vfr = true },
            xwayland = { force_zero_scaling = true },
            decoration = {
                blur = { enabled = false },
                shadow = { enabled = false },
            },
        })

        -- ===== Apps =====
        hl.bind("SUPER + Return",     hl.dsp.exec_cmd("kitty"),                  {description = "Launch kitty"})
        hl.bind("SUPER + T",          hl.dsp.exec_cmd("kitty"),                  {description = "Launch kitty"})
        hl.bind("SUPER + Space",      hl.dsp.exec_cmd("wofi -GiIS drun"),        {description = "Launcher"})
        hl.bind("SUPER + R",          hl.dsp.exec_cmd("wofi -GiIS drun"),        {description = "Launcher"})
        hl.bind("SUPER + A",          hl.dsp.window.close(),                     {description = "Close window"})
        hl.bind("SUPER + B",          hl.dsp.exec_cmd("firefox --private-window"), {description = "Firefox private"})
        hl.bind("SUPER + SHIFT + B",  hl.dsp.exec_cmd("firefox"),                {description = "Firefox"})
        hl.bind("SUPER + U",          hl.dsp.exec_cmd("vesktop"),                {description = "Vesktop"})
        hl.bind("SUPER + L",          hl.dsp.exec_cmd("hyprlock"),               {description = "Lock"})
        hl.bind("SUPER + Escape",     hl.dsp.exec_cmd("hyprctl dispatch exit"),  {description = "Quit Hyprland"})

        -- ===== Screenshots =====
        hl.bind("SUPER + SHIFT + S",  hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]), {description = "Region screenshot"})
        hl.bind("Print",              hl.dsp.exec_cmd([[grim - | wl-copy]]),               {description = "Fullscreen screenshot"})

        -- ===== Monitor layout swap =====
        hl.bind("CTRL + SUPER + Left",  hl.dsp.exec_cmd([[hyprctl keyword monitor "HDMI-A-1, preferred, 0x0, 1" && hyprctl keyword monitor "eDP-1, preferred, 1920x0, 1"]]))
        hl.bind("CTRL + SUPER + Right", hl.dsp.exec_cmd([[hyprctl keyword monitor "eDP-1, preferred, 0x0, 1" && hyprctl keyword monitor "HDMI-A-1, preferred, 1920x0, 1"]]))

        -- ===== Replay =====
        hl.bind("ALT + twosuperior", hl.dsp.exec_cmd("replay-save"))

        -- ===== Audio =====
        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), {locked = true, repeating = true})
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),        {locked = true, repeating = true})
        hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),       {locked = true})
        hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),     {locked = true})
        hl.bind("CTRL + XF86AudioMute", hl.dsp.exec_cmd([[notify-send 'Microphone' 'Mute toggled'; wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle]]), {locked = true})

        -- ===== Media =====
        hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
        hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
        hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

        -- ===== Window focus =====
        hl.bind("SUPER + left",  hl.dsp.focus({direction = "l"}))
        hl.bind("SUPER + right", hl.dsp.focus({direction = "r"}))
        hl.bind("SUPER + up",    hl.dsp.focus({direction = "u"}))
        hl.bind("SUPER + down",  hl.dsp.focus({direction = "d"}))

        -- ===== Workspaces (Belgian keyboard) =====
        hl.bind("SUPER + ampersand",  hl.dsp.focus({workspace = 1}))
        hl.bind("SUPER + eacute",     hl.dsp.focus({workspace = 2}))
        hl.bind("SUPER + quotedbl",   hl.dsp.focus({workspace = 3}))
        hl.bind("SUPER + apostrophe", hl.dsp.focus({workspace = 4}))
        hl.bind("SUPER + parenleft",  hl.dsp.focus({workspace = 5}))
        hl.bind("SUPER + section",    hl.dsp.focus({workspace = 6}))
        hl.bind("SUPER + egrave",     hl.dsp.focus({workspace = 7}))
        hl.bind("SUPER + exclam",     hl.dsp.focus({workspace = 8}))
        hl.bind("SUPER + ccedilla",   hl.dsp.focus({workspace = 9}))
        hl.bind("SUPER + agrave",     hl.dsp.focus({workspace = 10}))

        -- ===== Workspaces (Numpad) =====
        hl.bind("SUPER + KP_End",    hl.dsp.focus({workspace = 1}))
        hl.bind("SUPER + KP_Down",   hl.dsp.focus({workspace = 2}))
        hl.bind("SUPER + KP_Next",   hl.dsp.focus({workspace = 3}))
        hl.bind("SUPER + KP_Left",   hl.dsp.focus({workspace = 4}))
        hl.bind("SUPER + KP_Begin",  hl.dsp.focus({workspace = 5}))
        hl.bind("SUPER + KP_Right",  hl.dsp.focus({workspace = 6}))
        hl.bind("SUPER + KP_Home",   hl.dsp.focus({workspace = 7}))
        hl.bind("SUPER + KP_Up",     hl.dsp.focus({workspace = 8}))
        hl.bind("SUPER + KP_Prior",  hl.dsp.focus({workspace = 9}))
        hl.bind("SUPER + KP_Insert", hl.dsp.focus({workspace = 10}))

        -- ===== Move window to workspace (Belgian) =====
        hl.bind("SUPER + SHIFT + ampersand",  hl.dsp.window.move({workspace = 1,  follow = false}))
        hl.bind("SUPER + SHIFT + eacute",     hl.dsp.window.move({workspace = 2,  follow = false}))
        hl.bind("SUPER + SHIFT + quotedbl",   hl.dsp.window.move({workspace = 3,  follow = false}))
        hl.bind("SUPER + SHIFT + apostrophe", hl.dsp.window.move({workspace = 4,  follow = false}))
        hl.bind("SUPER + SHIFT + parenleft",  hl.dsp.window.move({workspace = 5,  follow = false}))
        hl.bind("SUPER + SHIFT + section",    hl.dsp.window.move({workspace = 6,  follow = false}))
        hl.bind("SUPER + SHIFT + egrave",     hl.dsp.window.move({workspace = 7,  follow = false}))
        hl.bind("SUPER + SHIFT + exclam",     hl.dsp.window.move({workspace = 8,  follow = false}))
        hl.bind("SUPER + SHIFT + ccedilla",   hl.dsp.window.move({workspace = 9,  follow = false}))
        hl.bind("SUPER + SHIFT + agrave",     hl.dsp.window.move({workspace = 10, follow = false}))

        -- ===== Move window to workspace (Numpad) =====
        hl.bind("SUPER + SHIFT + KP_End",    hl.dsp.window.move({workspace = 1,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Down",   hl.dsp.window.move({workspace = 2,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Next",   hl.dsp.window.move({workspace = 3,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Left",   hl.dsp.window.move({workspace = 4,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Begin",  hl.dsp.window.move({workspace = 5,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Right",  hl.dsp.window.move({workspace = 6,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Home",   hl.dsp.window.move({workspace = 7,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Up",     hl.dsp.window.move({workspace = 8,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Prior",  hl.dsp.window.move({workspace = 9,  follow = false}))
        hl.bind("SUPER + SHIFT + KP_Insert", hl.dsp.window.move({workspace = 10, follow = false}))

        -- ===== Workspace cycle =====
        hl.bind("SUPER + Tab",         hl.dsp.focus({workspace = "r+1"}))
        hl.bind("SUPER + SHIFT + Tab", hl.dsp.focus({workspace = "r-1"}))

        -- ===== Mouse =====
        hl.bind("SUPER + mouse:272", hl.dsp.window.drag(),   {mouse = true, description = "Window: Move"})
        hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {mouse = true, description = "Window: Resize"})
    '';
in
{
    programs.illogical-impulse = {
        enable = true;

        # Keep the user's own fish / kitty / starship modules; opt out of upstream's.
        dotfiles = {
            fish.enable = false;
            kitty.enable = false;
            starship.enable = false;
        };
    };

    # illogical-impulse's activation script rm -rfs ~/.config/hypr and copies end-4's
    # dotfiles in. home.file inside hypr/ would be wiped. This activation runs *after*
    # that copy and overwrites end-4's placeholder custom/keybinds.lua with our own.
    home.activation.userHyprlandCustom = config.lib.dag.entryAfter [ "copyIllogicalImpulseConfigs" ] ''
        $DRY_RUN_CMD mkdir -p "$HOME/.config/hypr/custom"
        $DRY_RUN_CMD install -m 0644 ${keybindsLua} "$HOME/.config/hypr/custom/keybinds.lua"
    '';
}
